### ISSUE TITLE
Problems with webpack 2 beta 25?

### ISSUE THREAD

**Issue by oscar-b** [iansinnott/react-static-webpack-plugin#16]
Trying to setup react-static-webpack-plugin for my small(ish) project, but can't get past this error: `TypeError: Cannot read property 'errors' of undefined`

I'm running "webpack": "^2.1.0-beta.25" but it seems it worked for @glennreyes in #14

Any idea on how to troubleshoot this further?

	C:\Dev\foo\node_modules\react-static-webpack-plugin\dist\utils.js:165
		if (childCompilation.errors && childCompilation.errors.length) {
							^

	TypeError: Cannot read property 'errors' of undefined
		at C:\Dev\foo\node_modules\react-static-webpack-plugin\dist\utils.js:165:27
		at Compiler.<anonymous> (C:\Dev\foo\node_modules\webpack\lib\Compiler.js:266:18)
		at Compiler.<anonymous> (C:\Dev\foo\node_modules\webpack\lib\Compiler.js:464:19)
		at C:\Dev\foo\node_modules\tapable\lib\Tapable.js:148:11
		at Compilation.<anonymous> (C:\Dev\foo\node_modules\webpack\lib\Compilation.js:443:11)
		at errorAndCallback (C:\Dev\foo\node_modules\webpack\lib\Compilation.js:343:3)
		at Compilation.<anonymous> (C:\Dev\foo\node_modules\webpack\lib\Compilation.js:364:11)
		at onDoneResolving (C:\Dev\foo\node_modules\webpack\lib\NormalModuleFactory.js:40:20)
		at C:\Dev\foo\node_modules\webpack\lib\NormalModuleFactory.js:117:20
		at C:\Dev\foo\node_modules\async\lib\async.js:726:13
		at C:\Dev\foo\node_modules\async\lib\async.js:52:16
		at done (C:\Dev\foo\node_modules\async\lib\async.js:241:17)
		at C:\Dev\foo\node_modules\async\lib\async.js:44:16
		at C:\Dev\foo\node_modules\async\lib\async.js:723:17
		at C:\Dev\foo\node_modules\async\lib\async.js:167:37
		at C:\Dev\foo\node_modules\webpack\lib\NormalModuleFactory.js:112:22
		at onResolved (C:\Dev\foo\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
		at loggingCallbackWrapper (C:\Dev\foo\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
		at afterInnerCallback (C:\Dev\foo\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
		at loggingCallbackWrapper (C:\Dev\foo\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
		at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Dev\foo\node_modules\tapable\lib\Tapable.js:108:46)
		at innerCallback (C:\Dev\foo\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
		at loggingCallbackWrapper (C:\Dev\foo\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
		at C:\Dev\foo\node_modules\tapable\lib\Tapable.js:210:15
		at C:\Dev\foo\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:39:4
		at loggingCallbackWrapper (C:\Dev\foo\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
		at afterInnerCallback (C:\Dev\foo\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
		at loggingCallbackWrapper (C:\Dev\foo\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
		at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Dev\foo\node_modules\tapable\lib\Tapable.js:108:46)
		at innerCallback (C:\Dev\foo\node_modules\enhanced-resolve\lib\Resolver.js:125:19)

**Comment by glennreyes** [comment]
@oscar-b I had to lock to `<2.1.0-beta.23` since it includes [several](https://github.com/webpack/webpack/issues/729) breaking changes. Would be really awesome if you could investigate further 🙌

**Comment by oscar-b** [comment]
By logging the `err` here: https://github.com/iansinnott/react-static-webpack-plugin/blob/master/src/utils.js#L127 I found the first problem (my `routes` parameter was defined as './app/routes.js` but should be just `./routes.js`. 

However there are still a lot of issues, and since I haven't used this before, I'm not sure it's my fault or some incompatiblity with for instance webpack 2.

For instance:
    Warning: getInitialState was defined on Component, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
    Warning: getInitialState was defined on Link, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

I'm also only getting just two html pages generated, one in the root (sv.html) and then one of the child pages (the last) generated as `v/index.html`

	export const routes = (<Route path="sv" component={App}>
		<IndexRoute component={Start} />
		<Route path="booking/" component={BookingClosed} />
		<Route path="about-us/" component={AboutUs} />
		<Route path="birthday/" component={Birthday} />
	</Route>);

**Comment by iansinnott** [comment]
Thanks for jumping in @glennreyes! I haven't yet tried out WP 2.x so this is all uncharted territory to me. 

@oscar-b thanks for raising this issue. I have no intention to try to support WP 2.x until it comes out of beta, which should be soon from what I know. But I'm certainly not ruling out this plugin as the source of your error, so do you have a repository where I can reproduce on my own?

Just a guess, you might try removing the trailing slash from your route `path`s and see if it then generates all the HTML files your expecting.

**Comment by oscar-b** [comment]
I'm not sure I will have any more time to spend on this either, I'm afraid. I guess we should wait until webpack 2 is released, seems like it's still very much in flux. Sorry no public repo of this.
