### ISSUE TITLE
Upgrade to React Router v2

### ISSUE THREAD

**Issue by iansinnott** [iansinnott/react-static-webpack-plugin#4]
React Router v2 is now out and stable, so it's time to upgrade. This should not mean discontinued support for v1, but docs and example app should be updated to ensure v2 support.

**Comment by iicdii** [comment]
Hi, I'm trying to use this plugin with react-router ^2.4.0.
I follow the example with react-router v1 and just changed like below
`if (typeof document !== 'undefined') {
  ReactDOM.render(
    <Router routes={routes} history={browserHistory} />,
    document.getElementById('root')
  );
}`

but I get Error like below
`[01:13:51] [webpack-dev-server] http://localhost:8080/webpack-dev-server/index.html
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:38
  return (0, _isUndefined2.default)(route.props.path) || (0, _isUndefined2.default)(route.props.component);`
`TypeError: Cannot read property 'path' of undefined
    at hasNoComponent (/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:38:48)
    at getNestedPaths (/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:71:7)
    at /Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:66:12
    at Array.map (native)
    at getNestedPaths (/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:65:51)
    at getNestedPaths (/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:75:24)
    at getAllPaths (/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/utils.js:79:37)
    at Compiler.<anonymous> (/Users/Harim/.nvm/versions/node/v5.11.0/lib/node_modules/react-static-webpack-plugin/dist/index.js:96:40)
    at Compiler.applyPluginsAsync (/Users/Harim/Develop/euplus/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/Harim/Develop/euplus/node_modules/webpack/lib/Compiler.js:226:7)`

So I wonder If I can't use it just changing browserhistory part.

**Comment by iansinnott** [comment]
Thanks @iicdii. I haven't had a chance to upgrade this yet but it's still on my todo list

**Comment by iicdii** [comment]
I've just downgrade react-router^1.0.3 and test in same way, I get same error just like before.
I think there is some problem with my project.

**Comment by iansinnott** [comment]
Hm, can you link me to the repo? I can figure out what's wrong if I'm able to reproduce.

The simple solution that might work is to run

```
rm -rf node_modules && npm install
```

😉

**Comment by scherler** [comment]
@iansinnott IMO you can close this issuem since in the package.json I see:  "react-router": "^2.4.0"

**Comment by iansinnott** [comment]
Ah thanks @scherler. Yup this should no longer be an issue
